### PR TITLE
React Tutorial : Todo 

### PR DESCRIPTION
**Pull request by Cabraham1**
### This pull request adds functionality to a React application that allows a user to add, edit, delete, and mark tasks as complete in a todo list.

**Created a Form component that allows a user to add and edit tasks**

**Created a TodosList component that displays the list of tasks, and allows a user to mark tasks as complete, edit tasks, and delete tasks**

**Created a Header component to display a title for the application**

**Used useState to manage the state of the todo list, the input for adding and editing tasks, and the task to be edited**

**Used useEffect to update local storage with the current todo list**

**Implemented conditional rendering to display the correct form button text and title based on whether a task is being added or edited**

### CODE REVIEW

**Comment by kkolade** [comment]
68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6d43496a436773336e575157664a5a7650412f67697068792d646f776e73697a65642d6c617267652e676966


## Comments
- No Linter error
- The App ran as expected
- Clean UI
- Folder structure is clean and well structured
## Required Change ♻️ 
- [ ] Please add a proper README.md
## Optional suggestions
-[ ] The input text style could be improved to show more contrast
-[ ] The use of React.StrictMode is encouraged in development so as to help in catching errors early

Every comment with the [OPTIONAL] prefix won't stop the approval of the PR. However, I strongly recommend you to take them into account as they can make your code better, and addressing them will really improve your application

Cheers and happy coding! 👍 👍 👍 

Feel free to leave any question or comment in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**Please, do not open a new Pull Request for re-review. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise**

---
https://github.com/Cabraham1/Todo-App/blob/0714908981ea96493985b72f59e630972c07fa9e/src/index.js#L4-L8

**Comment by Cabraham1** [comment]
Dear @kkolade,

I would like to express my gratitude for taking the time to review my work. Your feedback was extremely valuable, and I have incorporated all the changes you requested in the updated version.

Thank you once again for your help and support. I appreciate your time and effort.

**Comment by kkolade** [comment]
207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124

# Approved!
- There is nothing to add to your project
## Required Change ♻️ 
## Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of the PR. However, I strongly recommend you to take them into account as they can make your code better and addressing them will really improve your application

Cheers and happy coding! 👍 👍 👍 

Feel free to leave any question or comment in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**Please, do not open a new Pull Request for re-review. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise**

---

*As described in the [Code review limit policy](#) you have a limited number of reviews per project (Check the exact number in your dashboard). If  you think that this code review was not fair, you can request a second opinion using [this form](#).*

**Comment by Cabraham1** [comment]
thank you for reviewing my code @kkolade

**Pull request merged**
